[theme]

# Primary accent for interactive elements
primaryColor = '#8c8989'

# Background color for the main content area
backgroundColor = '#FFFFFF'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#e8e8e8'

# Color used for almost all text
textColor = '#000203'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"